# WARNING - Generated by {fusen} from dev/flat_save_data.Rmd: do not edit by hand

#' create_ts Create time series objects from downloaded and cleaned ABS time series data
#'
#' @param series A list returned from download_ts containing series and their metadata
#' @param name A series ID
#' @details This function creates the time series objects ready for extraction, seasonal adjustment or trending, or plotting.
#' @importFrom dplyr filter
#' @importFrom stats ts
#' @return A time series object
#' @export
create_ts <- function(series, name) {
  # Extract series data and metadata
  data <- series$data
  meta <- series$meta
  
  # Create common start and end periods
  common_start_year <-
    filter(meta, "series_id" == name)$common_start_year
  common_start_month <-
    filter(meta, "series_id" == name)$common_start_period
  common_end_year <- filter(meta, "series_id" == name)$common_end_year
  common_end_month <-
    filter(meta, "series_id" == name)$common_end_period
  
  # Redefine frequency variable
  freq <- filter(meta, "series_id" == name)$freq_num
  
  return(ts(
    data[, name],
    start = c(common_start_year, common_start_month),
    end = c(common_end_year, common_end_month),
    frequency = freq
  ))
}

#' create_ts_groups Create matching groups of series IDs
#'
#' @param series A list returned from download_ts containing series and their metadata
#' @details This function creates matching groups of series IDs from the metadata ('Index' tab of the downloaded ABS spreadsheet) corresponding to original, seasonally adjusted and trend series (in the 'Data1' tab of the spreadsheet). This is necessary to ensure matching series are plotted together by data item description. Note though that seasonally adjusted and trend series are not necessarily available for all original time series.
#' @importFrom dplyr filter pull
#' @return A list containing character vectors of matching groups of original, seasonally adjusted and trend series IDs
#' @export
create_ts_groups <- function(series) {
  # Extract series metadata
  meta <- series$meta
  
  # Extract series groups
  unique_series_names <- pull(unique(meta["data_item_description"]))
  
  # Initialise vectors to store matching series IDs by index number
  series_ID_orig <- character()
  series_ID_seas <- character()
  series_ID_tren <- character()
  
  # Cycle through each group of series
  for (name_index in 1:length(unique_series_names)) {
    # Filter data to extract current series group
    unique_name <- unique_series_names[name_index]
    data_filtered <-
      filter(meta, "data_item_description" == unique_name)
    
    # Cycle through each series in group
    for (row in 1:nrow(data_filtered)) {
      # Extract series type and populate vectors
      if (data_filtered[row, "series_type"] == "Original")
        series_ID_orig <-
          c(series_ID_orig, as.character(data_filtered[row, "series_id"]))
      if (data_filtered[row, "series_type"] == "Seasonally Adjusted")
        series_ID_seas <-
          c(series_ID_seas, as.character(data_filtered[row, "series_id"]))
      if (data_filtered[row, "series_type"] == "Trend")
        series_ID_tren <-
          c(series_ID_tren, as.character(data_filtered[row, "series_id"]))
    }
    
    # Insert blanks where series are absent in spreadsheet to ensure corresponding vectors of series IDs are aligned
    if (length(series_ID_orig) < name_index)
      series_ID_orig <- c(series_ID_orig, "")
    if (length(series_ID_seas) < name_index)
      series_ID_seas <- c(series_ID_seas, "")
    if (length(series_ID_tren) < name_index)
      series_ID_tren <- c(series_ID_tren, "")
  }
  
  return(list(
    orig = series_ID_orig,
    seas = series_ID_seas,
    tren = series_ID_tren
  ))
}
