# WARNING - Generated by {fusen} from dev/flat_save_data.Rmd: do not edit by hand

#' download_ts Download and clean ABS time series data
#'
#' @param url Download link to the data
#' @details The URL needs to be a link to the downloadable Excel file corresponding to a table on the webpage of an ABS publication, and not a link to the webpage itself. To obtain such a link (in Windows and using Microsoft Edge), navigate to the 'Data downloads' tab of a publication, right-click on the 'Download XLSX' hyperlink for the chosen table, and select 'Copy link'.
#' @importFrom dplyr filter mutate rename select_if slice_tail
#' @importFrom janitor clean_names
#' @importFrom lubridate month quarter year ymd
#' @importFrom readxl read_excel
#' @importFrom stats na.omit
#' @importFrom utils download.file
#' @return A list containing tibbles of series and their metadata
#' @export
download_ts <- function(url) {
  # Download data
  raw_data <- tempfile(fileext = ".xlsx")
  download.file(url, raw_data, method = "auto", mode = "wb")
  series_data <- read_excel(raw_data, sheet = "Data1", skip = 9) |>
    slice_tail(n = 500) |> # X-13 in 'seas' will fail if series is too long, so select most recent data
    rename(period = "Series ID") |>
    na.omit() # Some series have different start and end dates, so reduce dataset to complete cases across series
  
  # Download metadata
  series_metadata <-
    read_excel(raw_data,
               sheet = "Index",
               skip = 9,
               col_names = TRUE)
  
  # Remove irrelevant data
  series_metadata <- series_metadata |>
    filter(grepl("^[A-Z][a-z]+", "Data Item Description")) |> # Discard junk (empty and copyright) rows
    select_if( ~ !all(is.na(.))) |> # Discard empty columns
    clean_names()
  
  # Create common start and end dates across series
  series_metadata <- series_metadata |>
    mutate(
      common_series_start = series_data$period[1],
      common_series_end = series_data$period[nrow(series_data)],
      common_start_year = year(ymd("common_series_start")),
      common_start_period = ifelse("freq" == "Month", month(ymd(
        "common_series_start"
      )), quarter(ymd(
        "common_series_start"
      ))),
      common_end_year = year(ymd("common_series_end")),
      common_end_period = ifelse("freq" == "Month", month(ymd(
        "common_series_end"
      )), quarter(ymd(
        "common_series_end"
      )))
    )
  
  # Create numeric version of frequency variable
  series_metadata <- series_metadata |>
    mutate(freq_name = "freq",
           freq_num = ifelse("freq" == "Quarter", 4, 12)) |>
    within(rm("freq"))
  
  # Create variables for the publication and table titles
  titles <-
    read_excel(raw_data,
               sheet = "Index",
               range = "B5:B6",
               col_names = FALSE)
  title_pub <- as.character(titles[1, 1])
  title_tab <- as.character(titles[2, 1])
  series_metadata <- series_metadata |>
    mutate(publication = title_pub,
           table = title_tab)
  
  return(list(data = series_data, meta = series_metadata))
}
