# WARNING - Generated by {fusen} from dev/flat_save_data.Rmd: do not edit by hand

#' create_ts Create time series objects from downloaded and cleaned ABS time series data
#'
#' @param series A list returned from download_ts containing series and their metadata
#' @param type Optional: "S" for seasonally adjusted plots, or "T" for trend plots. Defaults to "S"
#' @details Requires the data output from download_ts, and calls the time series generation functions (create_groups and create_ts) during execution. Where an original series is not accompanied by seasonally adjusted or trend series, it will not be plotted as there is nothing to compare.
#' @importFrom dplyr filter
#' @importFrom ggplot2 aes element_text geom_line ggplot labs margin scale_x_date scale_y_continuous theme xlab ylab
#' @importFrom ggtext element_textbox_simple
#' @importFrom reshape2 melt
#' @importFrom RJDemetra x13
#' @importFrom seasonal seas
#' @return A list of ggplot objects
#' @export
#' @examples
#' \dontrun{
#' # Construct URL to download ABS data
#' ABS <- "https://www.abs.gov.au/statistics/economy/" # ABS website (for economic statistics)
#' pub <- "business-indicators/business-indicators-australia/" # Publication
#' ref <- "mar-2023/" # Reference period
#' cat <- "567600" # Catalogue number
#' tab <- "3.xlsx" # Table number
#' URL <- paste0(ABS, pub, ref, cat, tab)
#' 
#' # Download and plot data
#' sales <- download_ts(URL)
#' sales_plots <- plot_ts(sales, "T")
#' for (p in sales_plots) print(p)
#' }
plot_ts <- function(series,
                    type = "S") {
  # Extract series data and metadata
  data <- series$data
  meta <- series$meta
  
  # Initialise list to store plots
  plot_list <- list() # Length not known in advance since some iterations below are possibly skipped over
  
  # Extract groups and series IDs
  series_groups <- create_ts_groups(series)
  series_ID_orig <- series_groups$orig
  if (type == "S")
    series_ID_othr <- series_groups$seas
  if (type == "T")
    series_ID_othr <- series_groups$tren
  
  # Cycle through series
  for (series_index in 1:length(series_ID_orig)) {
    # Skip iteration when only the original series are present for a given group but not the SA or T series
    if (series_ID_othr[series_index] == "")
      next
    
    # Extract relevant series metadata for generating required series and for plotting purposes
    X13_type <- ifelse(type == "S", "seasonaladj", "trend")
    RJD_type <- ifelse(type == "S", "sa", "t")
    plot_type <- ifelse(type == "S", "Seasonally Adjusted", "Trend")
    series_description <-
      filter(meta, "series_id" == series_ID_othr[series_index])$data_item_description
    units <-
      filter(meta, "series_id" == series_ID_orig[series_index])$unit
    period_type <-
      ifelse(meta$freq_name[1] == "Quarter", "quarters", "months")
    period_range <-
      seq(data$period[1], data$period[nrow(data)], period_type)
    
    # Extract ABS original and seasonally adjusted/trend series
    ABS_orig <- create_ts(series, series_ID_orig[series_index])
    ABS <- create_ts(series, series_ID_othr[series_index])
    
    # Generate X-13ARIMA-SEATS seasonally adjusted/trend series
    X13 <-
      seas(ABS_orig, x11 = "")$data[, X13_type] # X11 option specifies X-11; overrides the 'seats' spec
    
    # Generate JDemetra+ seasonally adjusted/trend series
    RJD <- x13(ABS_orig, spec = "RSA5c")$final$series[, RJD_type]
    
    # Generate plot data
    plot_data <-
      data.frame(
        "ABS" = as.numeric(ABS),
        "X13" = as.numeric(X13),
        "RJD" = as.numeric(RJD),
        "Period" = as.Date(period_range)
      ) |>
      melt(
        id.vars = c("Period"),
        value.name = "Value",
        variable.name = "Method"
      )
    
    # Generate plot
    p <-
      ggplot(plot_data,
             aes(
               x = "Period",
               y = "Value",
               group = "Method",
               colour = "Method"
             )) +
      geom_line() +
      labs(title = series_description,
           subtitle = paste0(plot_type, " (", units, ")")) +
      theme(
        plot.title = element_textbox_simple(halign = 0.5, margin = margin(10, 0, 10, 0)),
        plot.subtitle = element_text(hjust = 0.5)
      ) + # 'element_textbox_simple' automatically wraps long titles
      xlab("") +
      ylab("") +
      scale_x_date(
        date_breaks = "5 years",
        date_labels = "%Y",
        date_minor_breaks = "1 year"
      ) +
      scale_y_continuous(labels = scales::comma_format())
    
    # Append plot to list of plots
    plot_list[[length(plot_list) + 1]] <- p
  }
  
  return(plot_list)
}
